use std::sync::Mutex;

// Serialize tests that modify global strategy state.
static TEST_MUTEX: Mutex<()> = Mutex::new(());

#[test]
fn threshold_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "threshold")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let (start, stop) = ferris_gc::threshold_local_start(ferris_gc::ThresholdConfig::default());
        s.borrow().change_strategy(start, stop);
    });
}

#[test]
fn threshold_with_custom_config_compiles() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify custom config works (same code the macro would generate)
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let config = ferris_gc::ThresholdConfig {
            gen0_threshold: 200,
            poll_interval: std::time::Duration::from_millis(100),
            ..ferris_gc::ThresholdConfig::default()
        };
        let (start, stop) = ferris_gc::threshold_local_start(config);
        s.borrow().change_strategy(start, stop);
    });
}

#[test]
fn adaptive_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "adaptive")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let (start, stop) = ferris_gc::adaptive_local_start(ferris_gc::AdaptiveConfig::default());
        s.borrow().change_strategy(start, stop);
    });
}

#[test]
fn adaptive_with_custom_config_compiles() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify custom config works (same code the macro would generate)
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let config = ferris_gc::AdaptiveConfig {
            initial_gen0_threshold: 200,
            min_threshold: 30,
            max_threshold: 5000,
            poll_interval: std::time::Duration::from_millis(100),
            ..ferris_gc::AdaptiveConfig::default()
        };
        let (start, stop) = ferris_gc::adaptive_local_start(config);
        s.borrow().change_strategy(start, stop);
    });
}

#[test]
fn basic_poll_interval_configurable() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify BASIC_POLL_INTERVAL_MS can be set (same code the macro would generate)
    ferris_gc::BASIC_POLL_INTERVAL_MS.store(200, std::sync::atomic::Ordering::Release);
    // Restore default
    ferris_gc::BASIC_POLL_INTERVAL_MS.store(50, std::sync::atomic::Ordering::Release);
}
