use std::sync::Mutex;

// Serialize tests that modify global strategy state.
static TEST_MUTEX: Mutex<()> = Mutex::new(());

#[test]
fn threshold_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "threshold")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let strategy = ferris_gc::threshold_local_strategy(ferris_gc::ThresholdConfig::default());
        s.borrow().set_strategy(strategy);
    });
}

#[test]
fn threshold_with_custom_config_compiles() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify custom config works (same code the macro would generate)
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let config = ferris_gc::ThresholdConfig {
            gen0_threshold: 200,
            poll_interval: std::time::Duration::from_millis(100),
            ..ferris_gc::ThresholdConfig::default()
        };
        let strategy = ferris_gc::threshold_local_strategy(config);
        s.borrow().set_strategy(strategy);
    });
}

#[test]
fn background_local_strategy_collects_on_owning_thread_without_racing() {
    // Regression: background_local_strategy used to spawn background threads that
    // collected the thread-local GC concurrently with its (lockless) mutator — a
    // data race that segfaults under load (tree_bench --strategy=background at
    // depth >= 18). The local strategy must collect on the owning thread only.
    // Allocating well past the collection threshold must not crash and must keep
    // live objects intact.
    use ferris_gc::Gc;
    let _guard = TEST_MUTEX.lock().unwrap();
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let strategy = ferris_gc::background_local_strategy(ferris_gc::BackgroundConfig::default());
        s.borrow().set_strategy(strategy);
    });
    // Drive many allocation-triggered collections while keeping a rolling live
    // set. A racing background collector would UAF/segfault here.
    let mut keep: Vec<Gc<i32>> = Vec::new();
    for i in 0..50_000 {
        let g = Gc::new(i);
        if i % 100 == 0 {
            keep.push(g);
        }
    }
    let sum: i64 = keep.iter().map(|g| ***g as i64).sum();
    std::hint::black_box(sum);
    assert_eq!(
        keep.len(),
        500,
        "live objects must survive on-thread collection"
    );
}

#[test]
fn adaptive_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "adaptive")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let strategy = ferris_gc::adaptive_local_strategy(ferris_gc::AdaptiveConfig::default());
        s.borrow().set_strategy(strategy);
    });
}

#[test]
fn adaptive_with_custom_config_compiles() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify custom config works (same code the macro would generate)
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let config = ferris_gc::AdaptiveConfig {
            initial_gen0_threshold: 200,
            min_threshold: 30,
            max_threshold: 5000,
            poll_interval: std::time::Duration::from_millis(100),
            ..ferris_gc::AdaptiveConfig::default()
        };
        let strategy = ferris_gc::adaptive_local_strategy(config);
        s.borrow().set_strategy(strategy);
    });
}

#[test]
fn basic_poll_interval_configurable() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify BASIC_POLL_INTERVAL_MS can be set (same code the macro would generate)
    ferris_gc::BASIC_POLL_INTERVAL_MS.store(200, std::sync::atomic::Ordering::Release);
    // Restore default
    ferris_gc::BASIC_POLL_INTERVAL_MS.store(50, std::sync::atomic::Ordering::Release);
}

#[test]
fn g1_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "g1")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let strategy = ferris_gc::g1_local_strategy(ferris_gc::G1Config::default());
        s.borrow().set_strategy(strategy);
    });
}

#[test]
fn g1_with_custom_config_compiles() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify custom config works (same code the macro would generate)
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let config = ferris_gc::G1Config {
            pause_target: std::time::Duration::from_millis(20),
            young_gen_threshold: 200,
            initiating_heap_occupancy_percent: 0.6,
            concurrent_mark_budget: 128,
            poll_interval: std::time::Duration::from_millis(100),
            ..ferris_gc::G1Config::default()
        };
        let strategy = ferris_gc::g1_local_strategy(config);
        s.borrow().set_strategy(strategy);
    });
}
