use std::sync::Mutex;

// Serialize tests that modify global strategy state.
static TEST_MUTEX: Mutex<()> = Mutex::new(());

#[test]
fn threshold_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "threshold")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let (start, stop) = ferris_gc::threshold_local_start(ferris_gc::ThresholdConfig::default());
        s.borrow().change_strategy(start, stop);
    });
}

#[test]
fn adaptive_strategy_setup_compiles_and_runs() {
    let _guard = TEST_MUTEX.lock().unwrap();
    // Verify the code generated by #[ferris_gc_main(strategy = "adaptive")] compiles
    ferris_gc::BASIC_STRATEGY_DISABLED.store(true, std::sync::atomic::Ordering::Release);
    ferris_gc::LOCAL_GC_STRATEGY.with(|s| {
        let (start, stop) = ferris_gc::adaptive_local_start(ferris_gc::AdaptiveConfig::default());
        s.borrow().change_strategy(start, stop);
    });
}
